# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main, dev, certification ]
  pull_request:
    branches: [ main, dev, certification ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm audit
      continue-on-error: true
    - run: npm ci
    - run: npm outdated
      continue-on-error: true
    - run: npm run eslint --if-present
    - run: npm run lint --if-present
    - run: npm run package
    - run: npm test
      env:
        CI: true
